### ISSUE TITLE
Opentype features

### ISSUE THREAD

**Issue by MuratKaribai** [arch1t3cht/Aegisub#106]
@arch1t3cht could you please add Opentype features because Chinese subtitles really need Stylistic Sets
![219932008-a831d065-ce13-4f27-85c2-c79691458c49](https://github.com/arch1t3cht/Aegisub/assets/40431755/5c743f21-b168-4344-845d-237bde52b2eb)

**Comment by arch1t3cht** [comment]
You don't need to ping me in issues, I already see them since they're on my repository.

Also, features like this are something Aegisub has no control over. This is a matter of the underlying subtitle renderers (VSFilter and libass).
