### ISSUE TITLE
Grid columns overlap

### ISSUE THREAD

**Issue by Jamato-sUn** [arch1t3cht/Aegisub#11]
![953_2022-11-06_15-39-57](https://user-images.githubusercontent.com/6930757/200171469-9d4fa53f-fa3d-494f-91f4-ea1203b75197.png)

I set grid font size to 16 and now the style name "Default" doesn't fit into it's column and overlaps the line text on every line.
I'm also using scaling of 125% in Windows and lowering it seems to make issue less prominent, but it's still there at 100%.

**Comment by arch1t3cht** [comment]
This is a known issue but should fix itself after changing the style of any line in the file, or simply restarting Aegisub. That's why the latest changelog contained "Restart Aegisub to fully apply these settings."

**Comment by Jamato-sUn** [comment]
Ah, I see, thanks! That helped

**Comment by arch1t3cht** [comment]
I've also pushed a fix to this bug now, which will be in the next release.
