### ISSUE TITLE
GridColumnTime may become too narrow…

### ISSUE THREAD

**Issue by 0tkl** [arch1t3cht/Aegisub#111]
…if your font shows proportional figures by default, and when the biggest time have multiple narrow figures (1).

![image](https://github.com/arch1t3cht/Aegisub/assets/118708188/2f8de1de-0e7d-4808-8b05-811097cc3fce)

Introduced in https://github.com/arch1t3cht/Aegisub/commit/eaf09b28501674bc3242e5ce011e362bb372ff23

**Comment by arch1t3cht** [comment]
Fun, I foresaw this exact issue too when adding this and specifically tested for it, but it didn't happen for me. Maybe I messed up when testing. Well, I'll just implement the workaround I had in mind for that.
