### ISSUE TITLE
Width of style editor window can't be resizable in Linux 

### ISSUE THREAD

**Issue by DarkHorus77** [arch1t3cht/Aegisub#114]
![Screenshot from 2024-02-29 22-29-16](https://github.com/arch1t3cht/Aegisub/assets/154360605/fdeb6cf7-1146-46db-8aab-f08296b8616a)

Resizing the style editor window only works for height. Width can't be resizable. The style editor window is taking up almost full width of the screen. I can't clearly see the style changes of subtitle. I can move to the window outside of the screen but it is not effective that much.

OS :  Linux Mint 21.3 x86_64
DE : Cinnamon 6.0.4
Kernel: 5.15.0-97-generic 
Display server : X11

**Comment by witchymary** [comment]
Works fine for me on Wayland + the wayland GDK backend

**Comment by DarkHorus77** [comment]
Haven't try it on wayland. Linux mint's experimental wayland support is almost unusable on my device and I also don't have intention of switching distro right now. 

But this is not a big deal. The rest functions are working fine.
