### ISSUE TITLE
xxhash-0.dll was not found

### ISSUE THREAD

**Issue by 3gf8jv4dv** [arch1t3cht/Aegisub#119]
I tried a [build](https://github.com/arch1t3cht/Aegisub/actions/runs/8539739104) based on the [da3c415](https://github.com/arch1t3cht/Aegisub/commit/da3c415e5f354e993ce421d83d1c9eedb5143479) commit of the feature branch.

On Microsoft Windows regardless of the wx variant, installer and portable variants, the System Error dialog pops up.

<details>
<summary>Preview</summary>

![0](https://github.com/arch1t3cht/Aegisub/assets/158490944/c23bce48-ef9b-4cf3-8917-de838c77e74e)

</details>

**Comment by arch1t3cht** [comment]
xxhash is a new dependency for a feature I just added a few hours ago. This CI run was the first run to test the build, and it looks like xxhash wasn't linked statically. I'm working on fixing this, but for now you can just use an artifact from an older run.

**Comment by arch1t3cht** [comment]
Fixed now
