### ISSUE TITLE
No video frame scrolling when zoomed

### ISSUE THREAD

**Issue by andiandi13** [arch1t3cht/Aegisub#14]
It has been an issue on Aegisub for ever, and it's very inconvenient.

If you zoom the frame too much, let's say to make an accurate \clip, you can't scroll to see what is outside the screen, so you have to use a lower zoom, and thus make a less accurate clip.

It would be great if you could add a scrollbar or some other workaround.

![2022-11-12 17_13_26-_ Untitled - Aegisub 9214, Daydream Cafe Edition  Shinon](https://user-images.githubusercontent.com/19387072/201483483-a8482476-ea71-4476-81a9-3fb9a2409425.jpg)

**Comment by seproDev** [comment]
Enable Video Panning under Advanced > Video in the settings. After that you can use CTRL + scroll wheel to zoom in to the video without increasing the size of the frame.
