### ISSUE TITLE
question: what is the difference between wx master and the one that doesn't say that? 

### ISSUE THREAD

**Issue by joskezelensky** [arch1t3cht/Aegisub#142]
I'm confused what version i should take, and what the difference is between them

**Comment by arch1t3cht** [comment]
As written in the release post:

> Add an option to build with the latest git version of wxWidgets instead of wxWidgets 3.1.7, and build wx master artifacts for Windows on the CI alongside the normal versions. This is relevant because wx master adds the option for an experimental dark mode on Windows. Thus, by downloading a wx master build instead of an ordinary one, enabling dark mode in the Options, and setting the rest of the UI colors in Options > Interface > Colors, you can now have a dark mode for Aegisub on Windows.
>
> Please note that this dark mode is an experimental feature from wxWidgets that uses undocumented Windows APIs. It's not perfect, and has all kinds of small rendering quirks. Some additional quirks come from wx master itself. Please do not report issues with dark mode or wx master specifically for now, since many of them cannot be fixed from Aegisub's side.
>
> EDIT: The biggest of those issues (flickering in the subtitle grid) has now been worked around on the latest CI builds.
>
> Thanks to seproDev for most of the work on the dark mode builds.

**Comment by joskezelensky** [comment]
thx
