### ISSUE TITLE
Last release doesn't include the AppImage version

### ISSUE THREAD

**Issue by justbispo** [arch1t3cht/Aegisub#164]
The past few releases included an AppImage version of the program, but not the last one.
I've noticed that the last workflow ran included an AppImage artifact, so I guess the missing AppImage in the last release was simply a mistake.

**Comment by arch1t3cht** [comment]
The AppImage artifact in the last workflow run did not work on my test machine. I didn't want to delay the release any further so I published without the AppImage for now and will investigate the issue soon.

**Comment by arch1t3cht** [comment]
Seems to be fixed now, I'll attach an AppImage to the release as soon as the workflow runs through.
