### ISSUE TITLE
make dependency control's forced auto update checks to be stopped or make it in background 

### ISSUE THREAD

**Issue by amanosatosi** [arch1t3cht/Aegisub#165]
i open some script and it pop up auto update check windows. it can't be closed. i press cancel and it take like a minute to close that. can you make it so it'll have an option where i open a script and dependency control won't force update check or doing those on background?

**Comment by arch1t3cht** [comment]
The problem is that automation scripts can modify the subtitle file, so they cannot simply run in the background while the user is also working on the file.
It is possible to disable DependencyControl's updates (or make them less frequent) in its config file (unfortunately there's no GUI for that, you'll have to edit the file yourself), see `updaterEnabled` in the documentation: https://github.com/TypesettingTools/DependencyControl

**Comment by amanosatosi** [comment]
> The problem is that automation scripts can modify the subtitle file, so they cannot simply run in the background while the user is also working on the file. It is possible to disable DependencyControl's updates (or make them less frequent) in its config file (unfortunately there's no GUI for that, you'll have to edit the file yourself), see `updaterEnabled` in the documentation: https://github.com/TypesettingTools/DependencyControl

can you just add an option to disable updater in aegisub instead of doing that?

**Comment by arch1t3cht** [comment]
No, DependencyControl is its own script and completely separate from Aegisub.

**Comment by amanosatosi** [comment]
> No, DependencyControl is its own script and completely separate from Aegisub.

okay so is that the one from

C:\Users\UserName\AppData\Roaming\Aegisub\config  ?

i changed the updater to false and it still don't work. full text file shows like this


`{"macros":{"ua.NecrosCopy":{"name":"NecrosCopy","configFile":"ua.NecrosCopy.json","namespace":"ua.NecrosCopy","requiredModules":{},"author":"reanimated","feed":"https:\/\/raw.githubusercontent.com\/unanimated\/luaegisub\/master\/DependencyControl.json","version":262400},"ua.JoinSplitSnap":{"name":"Join \/ Split \/ Snap","configFile":"ua.JoinSplitSnap.json","namespace":"ua.JoinSplitSnap","requiredModules":{},"author":"unanimated","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/unanimated-Aegisub-Scripts\/master\/DependencyControl.json","version":66048},"ua.Multiplexer":{"name":"Multiplexer","configFile":"ua.Multiplexer.json","namespace":"ua.Multiplexer","requiredModules":{},"author":"unanimated","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/unanimated-Aegisub-Scripts\/master\/DependencyControl.json","version":65792},"ua.Masquerade":{"name":"Masquerade","configFile":"ua.Masquerade.json","namespace":"ua.Masquerade","requiredModules":{},"author":"unanimated","feed":"https:\/\/raw.githubusercontent.com\/unanimated\/luaegisub\/master\/DependencyControl.json","version":196608},"ILL.Shapery":{"configFile":"ILL.Shapery.json","namespace":"ILL.Shapery","version":132358,"lastUpdateCheck":1731443514,"requiredModules":[{"feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/ILL-Aegisub-Scripts\/main\/DependencyControl.json","url":"https:\/\/github.com\/TypesettingTools\/ILL-Aegisub-Scripts\/","version":"1.3.2","moduleName":"clipper2.clipper2"},{"feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/ILL-Aegisub-Scripts\/main\/DependencyControl.json","url":"https:\/\/github.com\/TypesettingTools\/ILL-Aegisub-Scripts\/","version":"1.4.5","moduleName":"ILL.ILL"}],"author":"ILLTeam","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/ILL-Aegisub-Scripts\/main\/DependencyControl.json","name":"Shapery"},"garret.karaoke2alpha":{"author":"garret","configFile":"garret.karaoke2alpha.json","requiredModules":[{"moduleName":"aegisub.util"}],"namespace":"garret.karaoke2alpha","version":65792,"name":"K-Timing -> Alpha Timing"},"ua.Fadeworks":{"configFile":"ua.Fadeworks.json","namespace":"ua.Fadeworks","version":327680,"lastUpdateCheck":1731425357,"requiredModules":{},"author":"unanimated","feed":"https:\/\/raw.githubusercontent.com\/unanimated\/luaegisub\/master\/DependencyControl.json","name":"FadeWorkS"},"ua.BlurAndGlow":{"configFile":"ua.BlurAndGlow.json","namespace":"ua.BlurAndGlow","version":132352,"lastUpdateCheck":1731444523,"requiredModules":{},"author":"unanimated","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/unanimated-Aegisub-Scripts\/master\/DependencyControl.json","name":"Blur and Glow"},"ua.Colourise":{"name":"Colourise","lastUpdateCheck":1731444762,"version":327680,"configFile":"ua.Colourise.json","requiredModules":{},"author":"unanimated","feed":"https:\/\/raw.githubusercontent.com\/unanimated\/luaegisub\/master\/DependencyControl.json","namespace":"ua.Colourise"},"a-mo.Aegisub-Motion":{"author":"torque","channels":["DepCtrl"],"requiredModules":[{"moduleName":"aegisub.clipboard"},{"moduleName":"json"},{"version":"1.1.4","moduleName":"a-mo.ConfigHandler"},{"version":"1.0.2","moduleName":"a-mo.DataWrapper"},{"version":"1.3.0","moduleName":"a-mo.LineCollection"},{"version":"1.0.0","moduleName":"a-mo.Log"},{"version":"1.0.0","moduleName":"a-mo.Math"},{"version":"1.1.8","moduleName":"a-mo.MotionHandler"},{"version":"0.1.3","moduleName":"a-mo.Statistics"},{"version":"1.0.5","moduleName":"a-mo.TrimHandler"},{"version":"1.3.4","moduleName":"a-mo.Tags"}],"configFile":"a-mo.Aegisub-Motion.json","lastUpdateCheck":1731443451,"lastChannel":"DepCtrl","version":65545,"name":"Aegisub-Motion","url":"https:\/\/github.com\/TypesettingTools\/Aegisub-Motion","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/Aegisub-Motion\/DepCtrl\/DependencyControl.json","namespace":"a-mo.Aegisub-Motion"},"ua.Relocator":{"name":"Hyperdimensional Relocator","configFile":"ua.Relocator.json","namespace":"ua.Relocator","requiredModules":{},"author":"reanimated","feed":"https:\/\/raw.githubusercontent.com\/unanimated\/luaegisub\/master\/DependencyControl.json","version":263426},"l0.DependencyControl.Toolbox":{"configFile":"l0.DependencyControl.Toolbox.json","namespace":"l0.DependencyControl.Toolbox","version":259,"lastUpdateCheck":1731425392,"requiredModules":{},"author":"line0","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/DependencyControl\/master\/DependencyControl.json","name":"DependencyControl Toolbox"}},"modules":{"a-mo.Line":{"namespace":"a-mo.Line","configFile":"a-mo.Line.json","moduleName":"a-mo.Line","requiredModules":[{"moduleName":"aegisub.util"},{"moduleName":"json"},{"version":"1.0.0","moduleName":"a-mo.Log"},{"version":"1.3.3","moduleName":"a-mo.Tags"},{"version":"1.2.4","moduleName":"a-mo.Transform"}],"lastUpdateCheck":1731361814,"version":66819,"author":"torque","url":"https:\/\/github.com\/TypesettingTools\/Aegisub-Motion","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/Aegisub-Motion\/DepCtrl\/DependencyControl.json","name":"Line"},"a-mo.LineCollection":{"namespace":"a-mo.LineCollection","configFile":"a-mo.LineCollection.json","moduleName":"a-mo.LineCollection","requiredModules":[{"version":"1.0.0","moduleName":"a-mo.Log"},{"version":"1.5.2","moduleName":"a-mo.Line"}],"lastUpdateCheck":1731361815,"version":66304,"author":"torque","url":"https:\/\/github.com\/TypesettingTools\/Aegisub-Motion","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/Aegisub-Motion\/DepCtrl\/DependencyControl.json","name":"LineCollection"},"a-mo.TrimHandler":{"namespace":"a-mo.TrimHandler","configFile":"a-mo.TrimHandler.json","moduleName":"a-mo.TrimHandler","requiredModules":[{"version":"1.0.0","moduleName":"a-mo.Log"}],"lastUpdateCheck":1731361789,"version":65541,"author":"torque","url":"https:\/\/github.com\/TypesettingTools\/Aegisub-Motion","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/Aegisub-Motion\/DepCtrl\/DependencyControl.json","name":"TrimHandler"},"a-mo.Tags":{"namespace":"a-mo.Tags","configFile":"a-mo.Tags.json","moduleName":"a-mo.Tags","requiredModules":[{"version":"1.0.0","moduleName":"a-mo.Log"},{"version":"1.2.3","moduleName":"a-mo.Transform"}],"lastUpdateCheck":1731361733,"version":66308,"author":"torque","url":"https:\/\/github.com\/TypesettingTools\/Aegisub-Motion","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/Aegisub-Motion\/DepCtrl\/DependencyControl.json","name":"Tags"},"a-mo.Transform":{"namespace":"a-mo.Transform","configFile":"a-mo.Transform.json","moduleName":"a-mo.Transform","requiredModules":[{"version":"1.0.0","moduleName":"a-mo.Log"},{"version":"1.0.0","moduleName":"a-mo.Math"},{"version":"1.3.3","moduleName":"a-mo.Tags"}],"lastUpdateCheck":1731361797,"version":66052,"author":"torque","url":"https:\/\/github.com\/TypesettingTools\/Aegisub-Motion","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/Aegisub-Motion\/DepCtrl\/DependencyControl.json","name":"Transform"},"l0.DependencyControl":{"namespace":"l0.DependencyControl","configFile":"l0.DependencyControl.json","moduleName":"l0.DependencyControl","requiredModules":[{"feed":"https:\/\/raw.githubusercontent.com\/torque\/ffi-experiments\/master\/DependencyControl.json","version":"0.3.1","moduleName":"DM.DownloadManager"},{"feed":"https:\/\/raw.githubusercontent.com\/torque\/ffi-experiments\/master\/DependencyControl.json","version":"0.1.3","moduleName":"BM.BadMutex"},{"feed":"https:\/\/raw.githubusercontent.com\/torque\/ffi-experiments\/master\/DependencyControl.json","version":"0.1.5","moduleName":"PT.PreciseTimer"},{"feed":"https:\/\/raw.githubusercontent.com\/torque\/ffi-experiments\/master\/DependencyControl.json","version":"0.1.1","moduleName":"requireffi.requireffi"}],"lastUpdateCheck":1731361695,"version":1539,"author":"line0","url":"http:\/\/github.com\/TypesettingTools\/DependencyControl","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/DependencyControl\/master\/DependencyControl.json","name":"DependencyControl"},"DM.DownloadManager":{"namespace":"DM.DownloadManager","configFile":"DM.DownloadManager.json","moduleName":"DM.DownloadManager","requiredModules":{},"lastUpdateCheck":1731361695,"version":1280,"author":"torque","url":"https:\/\/github.com\/TypesettingTools\/ffi-experiments","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/ffi-experiments\/master\/DependencyControl.json","name":"DownloadManager"},"ILL.ILL":{"name":"ILL.ILL","configFile":"ILL.ILL.json","moduleName":"ILL.ILL","requiredModules":{},"unmanaged":true,"version":66569,"author":"ILLTeam","url":"https:\/\/github.com\/TypesettingTools\/ILL-Aegisub-Scripts\/","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/ILL-Aegisub-Scripts\/main\/DependencyControl.json","namespace":"ILL.ILL"},"PT.PreciseTimer":{"namespace":"PT.PreciseTimer","configFile":"PT.PreciseTimer.json","moduleName":"PT.PreciseTimer","requiredModules":{},"lastUpdateCheck":1731361695,"version":262,"author":"torque","url":"https:\/\/github.com\/TypesettingTools\/ffi-experiments","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/ffi-experiments\/master\/DependencyControl.json","name":"PreciseTimer"},"a-mo.Statistics":{"namespace":"a-mo.Statistics","configFile":"a-mo.Statistics.json","moduleName":"a-mo.Statistics","requiredModules":[{"moduleName":"json"},{"version":"1.0.0","moduleName":"a-mo.Log"}],"lastUpdateCheck":1731361789,"version":259,"author":"torque","url":"https:\/\/github.com\/TypesettingTools\/Aegisub-Motion","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/Aegisub-Motion\/DepCtrl\/DependencyControl.json","name":"Statistics"},"a-mo.DataHandler":{"namespace":"a-mo.DataHandler","configFile":"a-mo.DataHandler.json","moduleName":"a-mo.DataHandler","requiredModules":[{"version":"1.0.0","moduleName":"a-mo.Log"}],"lastUpdateCheck":1731361722,"version":65541,"author":"torque","url":"https:\/\/github.com\/TypesettingTools\/Aegisub-Motion","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/Aegisub-Motion\/DepCtrl\/DependencyControl.json","name":"DataHandler"},"BM.BadMutex":{"namespace":"BM.BadMutex","configFile":"BM.BadMutex.json","moduleName":"BM.BadMutex","requiredModules":{},"lastUpdateCheck":1731361695,"version":259,"author":"torque","url":"https:\/\/github.com\/TypesettingTools\/ffi-experiments","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/ffi-experiments\/master\/DependencyControl.json","name":"BadMutex"},"requireffi.requireffi":{"namespace":"requireffi.requireffi","configFile":"requireffi.requireffi.json","moduleName":"requireffi.requireffi","requiredModules":{},"lastUpdateCheck":1731361695,"version":258,"author":"torque","url":"https:\/\/github.com\/TypesettingTools\/ffi-experiments","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/ffi-experiments\/master\/DependencyControl.json","name":"requireffi"},"clipper2.clipper2":{"name":"clipper2.clipper2","configFile":"clipper2.clipper2.json","moduleName":"clipper2.clipper2","requiredModules":{},"unmanaged":true,"version":66560,"author":"ILLTeam","url":"https:\/\/github.com\/TypesettingTools\/ILL-Aegisub-Scripts","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/ILL-Aegisub-Scripts\/main\/DependencyControl.json","namespace":"clipper2.clipper2"},"a-mo.ConfigHandler":{"namespace":"a-mo.ConfigHandler","configFile":"a-mo.ConfigHandler.json","moduleName":"a-mo.ConfigHandler","requiredModules":[{"moduleName":"json"},{"version":"1.0.0","moduleName":"a-mo.Log"}],"lastUpdateCheck":1731361695,"version":65796,"author":"torque","url":"https:\/\/github.com\/TypesettingTools\/Aegisub-Motion","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/Aegisub-Motion\/DepCtrl\/DependencyControl.json","name":"ConfigHandler"},"a-mo.Math":{"name":"a-mo.Math","version":65536,"moduleName":"a-mo.Math","requiredModules":{},"unmanaged":true,"namespace":"a-mo.Math","configFile":"a-mo.Math.json"},"a-mo.DataWrapper":{"namespace":"a-mo.DataWrapper","configFile":"a-mo.DataWrapper.json","moduleName":"a-mo.DataWrapper","requiredModules":[{"version":"1.0.0","moduleName":"a-mo.Log"},{"version":"1.0.5","moduleName":"a-mo.DataHandler"},{"version":"1.0.1","moduleName":"a-mo.ShakeShapeHandler"}],"lastUpdateCheck":1731361879,"version":65538,"author":"torque","url":"https:\/\/github.com\/TypesettingTools\/Aegisub-Motion","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/Aegisub-Motion\/DepCtrl\/DependencyControl.json","name":"DataWrapper"},"a-mo.ShakeShapeHandler":{"namespace":"a-mo.ShakeShapeHandler","configFile":"a-mo.ShakeShapeHandler.json","moduleName":"a-mo.ShakeShapeHandler","requiredModules":[{"version":"1.0.0","moduleName":"a-mo.Log"}],"lastUpdateCheck":1731361722,"version":65538,"author":"torque","url":"https:\/\/github.com\/TypesettingTools\/Aegisub-Motion","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/Aegisub-Motion\/DepCtrl\/DependencyControl.json","name":"ShakeShapeHandler"},"a-mo.Log":{"name":"a-mo.Log","version":65536,"moduleName":"a-mo.Log","requiredModules":{},"unmanaged":true,"namespace":"a-mo.Log","configFile":"a-mo.Log.json"},"a-mo.MotionHandler":{"namespace":"a-mo.MotionHandler","configFile":"a-mo.MotionHandler.json","moduleName":"a-mo.MotionHandler","requiredModules":[{"version":"1.0.0","moduleName":"a-mo.Log"},{"version":"1.5.2","moduleName":"a-mo.Line"},{"version":"1.2.0","moduleName":"a-mo.LineCollection"},{"version":"1.0.0","moduleName":"a-mo.Math"},{"version":"1.3.3","moduleName":"a-mo.Tags"},{"version":"1.2.4","moduleName":"a-mo.Transform"}],"lastUpdateCheck":1731361789,"version":65800,"author":"torque","url":"https:\/\/github.com\/TypesettingTools\/Aegisub-Motion","feed":"https:\/\/raw.githubusercontent.com\/TypesettingTools\/Aegisub-Motion\/DepCtrl\/DependencyControl.json","name":"MotionHandler"}},"config":{"updaterRunning":false}}`

**Comment by arch1t3cht** [comment]
That does not say `"updaterEnabled": false` anywhere. The only related field is `updaterRunning`, which does something different.

**Comment by amanosatosi** [comment]
> That does not say `"updaterEnabled": false` anywhere. The only related field is `updaterRunning`, which does something different.

i have to add this? not just edit it?

**Comment by arch1t3cht** [comment]
Yes

**Comment by arch1t3cht** [comment]
There is a third-party script for editing the DependencyControl config here https://github.com/garret1317/aegisub-scripts/blob/master/garret.depctrl_config.lua

**Comment by amanosatosi** [comment]
> The management macro still doesn't exist, so i wrote one myself.

shots were fired

**Comment by amanosatosi** [comment]
ngl you should add that script in your future releases. it's pretty big problem. it's even more annoying than windows update. windows update don't come daily and it actually updates. but this one? chance of not updating is 99%. you can't use the app for a while. forced for every script that allow updating. trying to do motion track? you have to wait. wanna do fade effect in GUI? you have to wait. YOU WANT TO USE [SCRIPT NAME]? YOU HAVE TO WAIT. and it happen every time i turn my pc off and on again. it's just hell.
