### ISSUE TITLE
Isn't it support font's OpenType feature?

### ISSUE THREAD

**Issue by Yave-Yu** [arch1t3cht/Aegisub#167]
It losts all OpenType feature, such as basic one “kerning”.

**Comment by arch1t3cht** [comment]
First of all, this question is about the subtitle renderers (libass and VSFilter), not about Aegisub. Aegisub is only a program for editing subtitles, displaying them (as well as the rules for how they are displayed) is the job of the renderers.

Now, VSFilter, the reference renderer for the ASS format, does not support OpenType features, so libass doesn't either by default. As a special case, kerning can be enabled in libass by adding the header `Kerning: yes`, but note that this is specific to libass and will not be portable everywhere. For more information, see e.g. https://github.com/libass/libass/issues/652
