### ISSUE TITLE
Fold operation in Subtitle menu does not work

### ISSUE THREAD

**Issue by PhosCity** [arch1t3cht/Aegisub#17]
Built against this commit: https://github.com/arch1t3cht/Aegisub/commit/ac7635eb854353dee57726e17844c24ad2d39630
OS: Arch Linux

The fold operations like opening, closing and toggling works in right click menu but none of the fold operations in Subtitle menu works.

**Comment by arch1t3cht** [comment]
Thanks - will be fixed the next time I push to feature.
