### ISSUE TITLE
[Feature request] Show more info on the audio track list 

### ISSUE THREAD

**Issue by 04arm** [arch1t3cht/Aegisub#171]
When you open a file with multiple audio tracks, you have to choose the audio track you want from a list that looks like this:
```
Track 01: aac
Track 02: aac
Track 03: aac
Track 04: opus
Track 05: eac3
```
Choosing the right track would be easier if the list showed more information, like this:
```
Track 01: aac, 5.1, en: English
Track 02: aac, 2.0, en: English (SDH)
Track 03: aac, 2.0, en: English (DVD commentary)
Track 04: opus, 2.0, es-419: Spanish, Latin America (TV dub)
Track 05: eac3, 2.0, es-ES: Spanish, Spain
```
```
Track ##: codec, channels, language: Title
```

**Comment by arch1t3cht** [comment]
This has been requested a couple of times, but the libraries Aegisub uses to load audio and video (FFMS2, BestSource, etc) do not expose this information, so there's no easy way to do this.
