### ISSUE TITLE
Aegisub simply doesn't show up but it's there on Task Manager

### ISSUE THREAD

**Issue by masterkivat** [arch1t3cht/Aegisub#18]
Hi!
I'm facing a weird issue on my laptop, I just formatted it (Win10 - 22H2 x64) and I tried every single version of Aegisub (even yours!) and Aegisub window simply just doesn't show up, but it's claimed as "opened" on Task Manager...
My laptop is an Acer Aspire 5 (A515-41G-13U1 [link](https://canaltech.com.br/produto/acer/a515-41g-1480/))
Thanks in advance!~

**Comment by arch1t3cht** [comment]
Strange. I can't say I know what's happening, but here's a few general troubleshooting ideas.
- Does Aegisub show up in the task bar? Sometimes there's bugs where applications do open windows, but they're outside the visible area on screen. Or they're on some nonexistent second monitor.
- Do you have any plugins installed that could be failing to load? In fact, it might be worth it to delete your entire `%appdata%/Aegisub` folder or move it somewhere else and see if that helps.
- If those don't help - is there anything interesting in the log files that appear in `%appdata%/Aegisub/log`?

**Comment by masterkivat** [comment]
1) nope, it doesn't show up on task bar...
2) I tried moving the folder (as if it was deleted in the beggining) but nothing changed,,,
About 3, I attached the log below

[log.zip](https://github.com/arch1t3cht/Aegisub/files/10233540/log.zip)

**Comment by arch1t3cht** [comment]
Huh. Yeah, there's something going wrong there. Sadly, there's no good way to debug this since it's only happening on your machine.
For now, this is the only thing we can really do:
Can you download this build https://github.com/arch1t3cht/Aegisub/actions/runs/3704501854 (once it's done building in about an hour), run that, and send me those logs? I added more logging to diagnose where exactly it's getting stuck.

**Comment by masterkivat** [comment]
I just tried your new build and it didn't showed up but here are the logs:

[log.zip](https://github.com/arch1t3cht/Aegisub/files/10239495/log.zip)

**Comment by arch1t3cht** [comment]
So, I still don't know what exactly is happening, but I know that something is breaking when setting up the video display. (Even if no video is shown in the beginning, the display still gets initialized when starting Aegisub.) I made another build (https://github.com/arch1t3cht/Aegisub/actions/runs/3709502328) with even more detailed logging which you could run to find out where exactly it's getting stuck, but I'd guess that it's happening when setting up the OpenGL display. I'd wager that something about your OpenGL installation or your graphics drivers is broken. You could check the logs above to be sure.

**Comment by masterkivat** [comment]
I'm pretty sure it's something related to the AMD driver, I tried on my desktop PC (RTX 3080/Ryzen 5950x/64GB RAM@3600MHz), your Aegisub (like many others from other repos are) is working fine.
Unexpectedly I could make the original one (v.3.2.2) load on my laptop, but I really need to use things like Colourise and other tools in there...
I'll wait your build finishes and I'll reply again in the next minutes/hours.

**Comment by masterkivat** [comment]
I did something meanwhile...

>Runned DDU and uninstalled everything
>Downloaded and installed previous AMD Driver (Adrenalin 22.5.1 (WHQL))
>Rebooted the system and then I opened Aegisub
>*boom*
[log.zip](https://github.com/arch1t3cht/Aegisub/files/10242342/log.zip)
[log2.zip](https://github.com/arch1t3cht/Aegisub/files/10242356/log2.zip)
![aegisub-working-lmao](https://user-images.githubusercontent.com/43658221/208013457-44329118-4dd7-41ea-a959-7ceb53c3df18.png)

**Comment by arch1t3cht** [comment]
Yeah, then it was an OpenGL driver issue as I suspected.
I'm afraid there's nothing I can do against this from Aegisub's side since that part of OpenGL initialization happens entirely through wxWidgets.
So since you found the problem and were able to work around it I'll close the issue.

**Comment by masterkivat** [comment]
Thank you very much!
