### ISSUE TITLE
[Feature Release 09] Crash when new video gets loaded, while one is still opened

### ISSUE THREAD

**Issue by daed-alus** [arch1t3cht/Aegisub#23]
Feature Release 09
if you load a new video "directly" (drag n drop & select file from open dialog) while one is still opened, the application crashes
if you first close the old video, new one gets loaded normally

happens with mkv files and avs scripts

**Comment by arch1t3cht** [comment]
Does this happen consistently for any kind of video? I'm asking since I can't reproduce that.
Also, what do you have set for the audio and video providers in Preferences > Advanced > Audio / Video ?

**Comment by daed-alus** [comment]
yes happens everytime
both is set to ffmpeg

**Comment by daed-alus** [comment]
still happens with FR 10

**Comment by arch1t3cht** [comment]
Probably fixed, see https://github.com/arch1t3cht/Aegisub/issues/83#issuecomment-1763390396 for more information. Reopen if this still happens.
