### ISSUE TITLE
BUG: BestSource never works

### ISSUE THREAD

**Issue by ipid** [arch1t3cht/Aegisub#27]
Thanks for your Aegisub fork! Your fork has fixed a lot of bugs in Aegisub, and also integrated a lot of useful features that greatly improved my efficiency in creating subtitles.

Recently I found that **Aegisub always crashes after I set the audio or video source to BestSource**. ~I've tried every video on my computer, and no matter what kind of video I open, BestSource doesn't seem to work.~ FIX: I've tried many videos and it seems that video generated by Adobe Premiere makes BestSource crash.

![Screenshot: Change video source to BestSource](https://user-images.githubusercontent.com/5251264/218106152-c161608a-d7b8-4512-84c4-4f6ad516d689.png)

Is this a known issue, or is it just not working on my machine?

**Comment by seproDev** [comment]
I just attempted to use the BestSource video source on my machine and with every video I tried so far I first get the error messages `Timecodes are out of order` and then on scrubbing Aegisub crashes.

Using Windows 10 with the Feature Release 09.

Here the [crashlog.txt](https://github.com/arch1t3cht/Aegisub/files/10708067/crashlog.txt), though it's not really meaningful.

**Comment by ipid** [comment]
I had exactly the same bug as [@seproDev](https://github.com/seproDev)'s.

First I want to amend my statement: **not all videos cause BestSource to crash, but videos generated by Adobe Premiere do**. 

Here I got 2 videos. One is `Video-downloaded-from-Twitter.mp4` and another is `Video-generated-by-Adobe-Premiere.mp4`.

![image](https://user-images.githubusercontent.com/5251264/218133252-d29b69bf-66de-4818-aba3-db358dad9162.png)

I've set both `Video provider` and `Audio provider` to `BestSource`:

![screenshot](https://user-images.githubusercontent.com/5251264/218133150-00200afc-df9f-4a1d-864f-4687cbf3b1e2.png)

It opens the video from Twitter successfully but it outputs the length of each frame to be 1h20min:

![image](https://user-images.githubusercontent.com/5251264/218134600-d654e3b6-edb8-4bd7-962c-c653dd1c9afd.png)

And after opening the video from Premiere Pro, it reports `Timecodes are out of order`:

![image](https://user-images.githubusercontent.com/5251264/218134711-25dc786d-719c-4924-8e70-50b153bcd1a9.png)

When I try to seek a frame other than the first frame, Aegisub crashes:

![image](https://user-images.githubusercontent.com/5251264/218134916-c7c8ef3a-a8f2-4ad6-803b-4107b15b330c.png)

**Comment by arch1t3cht** [comment]
Thanks for the detailed report, this was a very dumb mistake. I'm surprised the previous state even worked for the videos I tested.
I pushed a fix that makes the two videos above work for me, you can try it on [this build](https://github.com/arch1t3cht/Aegisub/actions/runs/4163505048).
Github autoclosed the issue after I pushed, but feel free to reopen it if there's still more issues.

**Comment by seproDev** [comment]
Tested out the build and most videos work now.
I still have this one video which crashes similarly, but only if it is the first video loaded.
To replicate. Delete the `bsindex` folder and to load [this](https://cdn.discordapp.com/attachments/887022475777572885/1074688817266688050/bad_subs.mp4) video. The error message is `Couldn't read frame!`

**Comment by arch1t3cht** [comment]
Yup, done.
