### ISSUE TITLE
Feature release 09 build fail

### ISSUE THREAD

**Issue by Pro-pra** [arch1t3cht/Aegisub#28]
That version of wxgtk needed? on build stage i see error:
```
DEBUG: ../src/crash_writer.cpp:78:16: error: ‘class {anonymous}::StackWalker’ has no member named ‘WalkFromException’
DEBUG:    78 |         walker.WalkFromException();
```
i use wxgtk-3.1.5

**Comment by arch1t3cht** [comment]
Any recent wxgtk should work. The [Ubuntu workflows on the CI1](https://github.com/arch1t3cht/Aegisub/actions) use 3.0, for example.
The error looks like some issue with your version of wxwidgets, but I can't really diagnose it without knowing more.

**Comment by Pro-pra** [comment]
From previous version we have patch deleted stackwalker, i restore this patch.
