### ISSUE TITLE
vector clip

### ISSUE THREAD

**Issue by eddilara** [arch1t3cht/Aegisub#31]
can we get someway to move a vector clip

**Comment by seproDev** [comment]
Is this what you want?

https://user-images.githubusercontent.com/4618135/219616182-9fdc3622-aaeb-4008-ae29-6aae80953e30.mp4

**Comment by eddilara** [comment]
sorta...I wanna be able to use the move tag on it.....

**Comment by seproDev** [comment]
Ah, okay. Yes, while rect clips can be animated with `\t`, you can't do that with vector clips. This also isn't something Aegisub can change, as it would require changes to the ASS specification.

If you want an animated vector clip, you need to FBF the line.

**Comment by arch1t3cht** [comment]
As sepro said, this is not something that can be changed from Aegisub's side.
