### ISSUE TITLE
Feature: motion tracker

### ISSUE THREAD

**Issue by eddilara** [arch1t3cht/Aegisub#33]
can you take some code from other open source projects and make a motion tracker for aegisub
the main branch of aegisub has been saying they are gonna add a motion tracker for like 10 years

**Comment by seproDev** [comment]
You mean [Aegisub Motion](https://github.com/TypesettingTools/Aegisub-Motion)?

**Comment by arch1t3cht** [comment]
This would be a gigantic undertaking and in no way worth it when there is already dedicated software allowing for motion tracking that's already been integrated well by existing automation scripts.

It's a similar story for a gradient creator. While this one is vaguely reasonable, any built-in solution would likely only allow for a subset of the functionality that users might know from scripts. If anything, I'd rather expand the Lua API to allow for some kind of visual controls and live preview, but even that is only a vague idea so far.
