### ISSUE TITLE
OCR

### ISSUE THREAD

**Issue by eddilara** [arch1t3cht/Aegisub#35]
how about ocring of hardsubs....you could use the same library's as subtitle edit

**Comment by arch1t3cht** [comment]
Please stop opening issues with requests for gigantic feature additions such as these.

I will only consider working on features that
- I have the time and resources to add
- can be implemented in some complete and satisfying manner
- are actually necessary, in particular not already handled well by better external tools
- fit into Aegisub. The program shouldn't be some random collection of half-complete features. Things that can be an automation script should probably be one.

OCR fails on every one of these counts.
