### ISSUE TITLE
Hardware-accelared Decoding

### ISSUE THREAD

**Issue by eddilara** [arch1t3cht/Aegisub#37]
another feature that would be very useful
https://github.com/Ristellise/AegisubDC/issues/51

**Comment by arch1t3cht** [comment]
Same as #35 .

FFmpegSource does not support hardware decoding. BestSource does in theory and maybe I could expose the option for that, but it being BestSource there is no way this would yield a performance improvement over simply software decoding with other sources.

I already added Vapoursynth support, which can be used to run any video source you want, including hardware-accelerated ones.
