### ISSUE TITLE
hard to explain feature from OCR'd bd subs

### ISSUE THREAD

**Issue by eddilara** [arch1t3cht/Aegisub#39]
this feature might be impossible to do...figured id ask anyway
a feature where aegisub could auto fix subs that have been OCR'd from bd or dvd subs

example

Default,,0,0,0,,Miss Stupid.
Dialogue: 0,0:04:34.67,0:04:34.91,Default,,0,0,0,,Komugi Nakahara's Grave\NMiss Stupid.
Dialogue: 0,0:04:34.94,0:04:36.38,Default,,0,0,0,,Komugi Nakahara's Grave\NWhat did you say?!
Dialogue: 0,0:04:36.40,0:04:38.85,Default,,0,0,0,,Komugi Nakahara's Grave We went deep into\Nthe red because her jobs were canceled.
Dialogue: 0,0:04:38.87,0:04:39.62,Default,,0,0,0,,Komugi Nakahara's Grave

would be nice if it could separate the lines on the correct time..and merge them
or maybe it would notice the lines...and then give the user the ability in a window to fix it...maybe have the program do what it thinks is correct..and then let the user fix it if necessary

**Comment by arch1t3cht** [comment]
Same as #35 . You're also very spot on with your hunch that this might be hard to do right. If the feature is too hard to explain in words, how do you expect someone to implement it in code?

So this feature also fails at least two of the points explained in #35 . With a concrete and formal description of what kind of errors you want to fix, this can easily be made into an automation script, but it does not belong into Aegisub.
