### ISSUE TITLE
new guide

### ISSUE THREAD

**Issue by eddilara** [arch1t3cht/Aegisub#41]
I found a really nice NEW guide for tags in aegisub
might be good to repost it on github and then link to it from the help menu

https://blog.mmf.moe/post/libass-tags/

**Comment by seproDev** [comment]
Now that aegisub.org is somewhat back up and running, I think improvements to the documentation should rather be made there.
https://aegisub.org/docs/latest/ass_tags/
https://github.com/Aegisub/aegisite

**Comment by arch1t3cht** [comment]
On top of that, that website is not in English, so it doesn't make much sense to link to it.
