### ISSUE TITLE
Ninja error on Fedora 37

### ISSUE THREAD

**Issue by pr1maryuser** [arch1t3cht/Aegisub#49]
Attempting to compile and install on Fedora Workstation 37, ninja fails with the error message "You do not have support for any sources of high quality entropy"

Here is the full output of ninja:

[2/1090] Compiling C object subproject...t.a.p/src_expat_expat_lib_xmlparse.c.o
FAILED: subprojects/wxWidgets/libwxexpat.a.p/src_expat_expat_lib_xmlparse.c.o 
ccache cc -Isubprojects/wxWidgets/libwxexpat.a.p -Isubprojects/wxWidgets -I../subprojects/wxWidgets -Isubprojects/wxWidgets/__CMake_build/lib/wx/include/gtk3-unicode-3.1 -I../subprojects/wxWidgets/__CMake_build/lib/wx/include/gtk3-unicode-3.1 -Isubprojects/wxWidgets/__CMake_build -I../subprojects/wxWidgets/__CMake_build -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -fPIC -O3 -DNDEBUG -pthread -D_UNICODE -MD -MQ subprojects/wxWidgets/libwxexpat.a.p/src_expat_expat_lib_xmlparse.c.o -MF subprojects/wxWidgets/libwxexpat.a.p/src_expat_expat_lib_xmlparse.c.o.d -o subprojects/wxWidgets/libwxexpat.a.p/src_expat_expat_lib_xmlparse.c.o -c ../subprojects/wxWidgets/src/expat/expat/lib/xmlparse.c
../subprojects/wxWidgets/src/expat/expat/lib/xmlparse.c:100:4: error: #error You do not have support for any sources of high quality entropy enabled. For end user security, that is probably not what you want. Your options include: * Linux >=3.17 + glibc >=2.25 (getrandom): HAVE_GETRANDOM, * Linux >=3.17 + glibc (including <2.25) (syscall SYS_getrandom): HAVE_SYSCALL_GETRANDOM, * BSD / macOS >=10.7 (arc4random_buf): HAVE_ARC4RANDOM_BUF, * BSD / macOS (including <10.7) (arc4random): HAVE_ARC4RANDOM, * libbsd (arc4random_buf): HAVE_ARC4RANDOM_BUF + HAVE_LIBBSD, * libbsd (arc4random): HAVE_ARC4RANDOM + HAVE_LIBBSD, * Linux (including <3.17) / BSD / macOS (including <10.7) (/dev/urandom): XML_DEV_URANDOM, * Windows >=Vista (rand_s): _WIN32. If insist on not using any of these, bypass this error by defining XML_POOR_ENTROPY; you have been warned. If you have reasons to patch this detection code away or need changes to the build system, please open a bug. Thank you!
  100 | #  error You do not have support for any sources of high quality entropy \
      |    ^~~~~
[19/1090] Compiling C++ object subproj...src_stc_scintilla_lexers_LexHTML.cxx.o
ninja: build stopped: subcommand failed.

**Comment by arch1t3cht** [comment]
This is an issue in compiling wxwidgets, not Aegisub. The error message more or less explains what to do.
But, are you sure that you want to compile wxwidgets manually here? Instead of linking against an installed version of wxwidgets? If you install wx from your distribution, Aegisub's build system should pick that up and won't need to compile it itself. Same for most other dependencies.
