### ISSUE TITLE
Font Loading Issue and a minor display problem

### ISSUE THREAD

**Issue by Amne3ia** [arch1t3cht/Aegisub#50]
1. Font loading issue: Regardless of whether I use the software to mount fonts or install them directly, I'm unable to access them in this version of Aegisub. As shown in the attached screenshot, the font style appears as on the right-hand side.
![01](https://user-images.githubusercontent.com/130724761/231953944-5a06ceb5-fc36-4eb5-8cbd-8220c2d161c4.png)

2. Inconsistent display between the right-click menu and the bottom panel.
https://user-images.githubusercontent.com/130724761/231954097-162994b5-c2c9-4d46-90be-98d2c46e116a.mp4

I'm using a portable version of Aegisub on a Windows operating system. Additionally, I previously had the Daydream Cafe version of Aegisub installed. Although I believe I've uninstalled it completely, the issues mentioned above may be related to this previous installation.

**Comment by arch1t3cht** [comment]
Thanks for reminding me of the second issue. I noticed this a while ago, but it was before I started this fork, so I forgot about it. I'll check it out.

For the first issue, what subtitle provider do you have selected? Can you try seeing how switching providers affects this?

**Comment by Amne3ia** [comment]
I was previously using CSRI/vsfilter_textsub. I tried switching subtitle providers and found that the font loading issue was resolved when using libass.However, I asked a friend who's using the official 3.2.2 version of Aegisub, and they were able to load the same font with CSRI/xy-vsfilter_aegisub.

**Comment by arch1t3cht** [comment]
Closing since this was fixed with feature_10.
