### ISSUE TITLE
scrambled video when decoding vp9 frame with threads > 1 or == -1

### ISSUE THREAD

**Issue by XeroAlpha** [arch1t3cht/Aegisub#58]
Same as https://github.com/wangqr/Aegisub/issues/32 and https://github.com/FFMS/ffms2/issues/352, but it seems changing "Decoding Threads" to 1 fixes it. It seems that [video_provider_ffmpegsource.cpp#234](https://github.com/arch1t3cht/Aegisub/blob/0548845c3e6bf37cf20df05c9c22de52ffb68e44/src/video_provider_ffmpegsource.cpp#L234) is not working.

![image](https://github.com/arch1t3cht/Aegisub/assets/22394706/4dde22af-7ee1-4c2f-b933-52f955f47ca5)

```
PS > ffprobe TestVideo.webm
Input #0, matroska,webm, from 'TestVideo.webm':
  Metadata:
    ENCODER         : Lavf60.3.100
  Duration: 00:02:24.03, start: 0.000000, bitrate: 781 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1920x1080, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn (default)
    Metadata:
      DURATION        : 00:02:24.000000000
  Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
    Metadata:
      DURATION        : 00:02:24.028000000
```

**Comment by arch1t3cht** [comment]
What version and what OS is this? This is an upstream issue in ffms2, but I already switched the ffms2 wrap to [a fork](https://github.com/arch1t3cht/FFMS2) that merges the draft pr's that fix/work around this issue and some others.

Judging by the terminal prompt it looks like you're on Windows, where this is already fixed on `feature`: https://github.com/arch1t3cht/Aegisub/actions . It should also be fixed for the CI artifacts on other operating systems, though that hasn't been tested as much. Alternatively, you can manually compile with `--force-fallback-for=ffms2` or just install the above fork yourself.

**Comment by XeroAlpha** [comment]
I used to use feature-9 (latest release), now I switched to the artifact from the latest action, and all the issues have been fixed. Thank you very much!

**Comment by arch1t3cht** [comment]
@XeroAlpha sorry but you might want to update one more time to the [latest CI build](https://github.com/arch1t3cht/Aegisub/actions/runs/5338179043). The last one had a critical regression which I fixed now.
