### ISSUE TITLE
Kerning not applying when using color tags between letters

### ISSUE THREAD

**Issue by TealRabbit19** [arch1t3cht/Aegisub#59]
When kerning is enabled in Script Info, it breaks when text color changes between characters in a kerning pair.
For example, my font has a kerning pair for 'wa,' and if there is a color tag between these two letters, for example: `w{\c&H1B61AF&}a` the kerning reverts as if none has been set. This particularly causes issues with typesetting signs on multiple layers where one layer is all the same color but another layer is not.

OS: Windows 11
Version: Aegisub 9530-cibuilds-79a0655eb

Kerning: Yes  in Script Info for both these screenshots:
![with color tag](https://github.com/arch1t3cht/Aegisub/assets/136912798/c3808a03-7569-46da-bd55-f852105b4740)
![nocolortag](https://github.com/arch1t3cht/Aegisub/assets/136912798/b7516baa-f22a-468a-b583-3f499a6a16a5)
Closeup better showing the kerning of layer 2 has changed but layer 1 is fine:
![sidebyside](https://github.com/arch1t3cht/Aegisub/assets/136912798/59b6b57e-3069-426c-8f45-7f7c889d28ed)

**Comment by arch1t3cht** [comment]
This has to do with libass/VSFilter and not Aegisub, and is also mostly intended. See https://github.com/libass/libass/issues/648#issuecomment-1424138512 for more discussion.
