### ISSUE TITLE
Dark theme on AegisubDC doesn't work

### ISSUE THREAD

**Issue by SorrHash** [arch1t3cht/Aegisub#60]
![kmolm](https://github.com/arch1t3cht/Aegisub/assets/114016987/ab814c95-cf71-4135-8c5b-7cbb81d7726a)

Any Help?

**Comment by arch1t3cht** [comment]
This is not AegisubDC.

**Comment by SorrHash** [comment]
> 

I download it from here https://github.com/Ristellise/AegisubDC

**Comment by arch1t3cht** [comment]
And that is not my repository, which is why I cannot help you.

**Comment by SorrHash** [comment]
> 

Oops Wrong repository Sorry,Iam very sorry
