### ISSUE TITLE
Aegisub will crash if loaded avs without audio

### ISSUE THREAD

**Issue by seiya-git** [arch1t3cht/Aegisub#61]
When loading avs script, I got this error and Aegisub will crash 
![](https://i.imgur.com/nBpuAGi.png)

Default vapoursynth audio script:
import vapoursynth as vs
vs.core.bas.Source(source=filename).set_output()

**Comment by arch1t3cht** [comment]
Does this still happen with the updated provider loading logic? If so, can you give detailed steps to reproduce?

**Comment by seiya-git** [comment]
![image](https://github.com/arch1t3cht/Aegisub/assets/7394323/45f55e23-0b35-4cb3-a5ba-d63e63b843f8)
Yes

just trying open avs as video file:
`FFMS2("any_video.mp4", atrack=-2)`

**Comment by arch1t3cht** [comment]
Should be fixed now, see https://github.com/arch1t3cht/Aegisub/issues/83#issuecomment-1763390396 for more information. Reopen if this still happens.

**Comment by seiya-git** [comment]
@arch1t3cht not fixed for me

when dran-n-drop avisynth script:
![image](https://github.com/arch1t3cht/Aegisub/assets/7394323/ef749296-18df-4d58-8595-e6dad082d913)
after selecting any of them, it's get error
![image](https://github.com/arch1t3cht/Aegisub/assets/7394323/1839d397-ca60-4f29-ae83-705b3fff5cae)
![image](https://github.com/arch1t3cht/Aegisub/assets/7394323/d5e3571b-9fe7-4194-a27e-e6d2067387dc)
and after closing error window and click play, Aegisub silently closes

**Comment by arch1t3cht** [comment]
I see, that was a separate issue with the avisynth wrap on top of the audio/video provider selection issue. Fixed now.

**Comment by seiya-git** [comment]
Thanks, with 858f4acf it's working now
