### ISSUE TITLE
Something wrong with high resolution scaling

### ISSUE THREAD

**Issue by Lambholl** [arch1t3cht/Aegisub#76]
P1: arch1t3cht/Aegisub
P2: Ristellise/AegisubDC
P3: AmusementClub/Aegisub

![Z4FL(3OFTXGX6KVYGH%` N2](https://github.com/arch1t3cht/Aegisub/assets/55140169/7bc3d4bb-5471-4a45-94ed-60f696759814)
![2T6$V}}HV6WNCH4YX~$TDYC](https://github.com/arch1t3cht/Aegisub/assets/55140169/d5149e00-69d6-47c9-9f7a-4721210c2205)
![%(Z9IT9E(29AI$_W7G1~TPL](https://github.com/arch1t3cht/Aegisub/assets/55140169/25d82626-8772-477c-ba99-f4b291932bf3)

**Comment by arch1t3cht** [comment]
The "Toolbar Icon Size" still needs to be set manually on this fork. The other forks scale it automatically on Windows, but I ran into complications with this.
