### ISSUE TITLE
ERROR: Subproject "subprojects/icu" required but not found.

### ISSUE THREAD

**Issue by KingTimer12** [arch1t3cht/Aegisub#80]
How i resolve this?

![image](https://github.com/arch1t3cht/Aegisub/assets/40837742/5eb4a947-33ac-41a8-be9b-14fe0b0a711d)

**Comment by arch1t3cht** [comment]
Try passing `--Dharfbuzz:icu=disabled` as is done [in the ci runs](https://github.com/arch1t3cht/Aegisub/blob/11fece4c0304e79912b0ada2533ca2bbb5d435a6/.github/workflows/ci.yml#L28-L43).

**Comment by KingTimer12** [comment]
Yo! Thanks. The problem with the meson was solved, but this new problem appeared when executing the ninja command
![image](https://github.com/arch1t3cht/Aegisub/assets/40837742/938771f3-6c66-4007-964a-880ae960a017)

**Comment by arch1t3cht** [comment]
This is due to a recent change in luajit. For now you can roll back luajit to a previous version or apply the change proposed in #79 . I just didn't have the time to review and merge that PR yet.

**Comment by KingTimer12** [comment]
Even with the PR it didn't work, the error continues. I'll take your advice first and get an old version

**Comment by arch1t3cht** [comment]
Ah, right, if you're following the PR you'd need to delete the `subprojects/luajit` directory after applying the changes, since the PR modifies the patch files.

**Comment by KingTimer12** [comment]
Delete the `subprojects/luajit.wrap`?

**Comment by arch1t3cht** [comment]
No, the folder `subprojects/luajit`. To force meson to redownload it and apply the updated packagefiles.

**Comment by KingTimer12** [comment]
Right, I did that, but the new error I reported above remains

**Comment by KingTimer12** [comment]
worked! Ty for help
