### ISSUE TITLE
Aegisub crashing out with "Vector too long" error

### ISSUE THREAD

**Issue by magnilens** [arch1t3cht/Aegisub#83]
Aegisub version: Feature release 10

When I try to open this video in Aegisub, it just dies with that "vector too long" messagebox. It's just a black rectangle for 24 frames. I cut it out from a longer video that played fine on its own. I also tried stitching several copies of this video together to see if a longer one was playable, it wasn't. Same error.

[Sample](https://github.com/arch1t3cht/Aegisub/files/12642587/blank.zip)

**Comment by arch1t3cht** [comment]
I can't reproduce this with your file, it loads fine for all normal video providers. What OS and what Audio/Video providers are you using?

**Comment by magnilens** [comment]
I'm using windows 10 and FFMPEGSource as the audio and video provider, according to aegisub's advanced preferences window, anyway.

**Comment by seiya-git** [comment]
Did you try open video drag n drop or via menu?

**Comment by magnilens** [comment]
It was both drag n drop and right click menu on Explorer. However, opening the video through Aegisub's menu had no problems. I had some other 1 second videos I made to be used as thumbnails. They also encountered problems if I used drag and drop or right click menu to open them in Aegisub. But also no problems when using the menu instead.

At least I know there isn't a problem with the video files now.

**Comment by seiya-git** [comment]
@magnilens your videos have audio tracks? It seems to me that this bug appears when there is no audio track in video file.

**Comment by magnilens** [comment]
You're right! I just tested with a few video files with and without their audio tracks. Those without audio tracks will cause this bug when dropped into Aegisub or if opened via "Open With" in Explorer.

**Comment by seiya-git** [comment]
So #61 is same bug

@arch1t3cht, more info about the bug

**Comment by arch1t3cht** [comment]
I found the issue now, as well as the reason why I couldn't reproduce it before. The default value for the audio provider is `ffmpegsource` (mind the lowercase), while the provider's name is `FFmpegSource`. This trips up the provider selection. As soon as you change the default audio provider setting within Aegisub once, the issue disappears.

Still, I'll fix some stuff to make this less likely to happen.
