### ISSUE TITLE
Word selection box display on edge instead of typing area

### ISSUE THREAD

**Issue by bccaption2** [arch1t3cht/Aegisub#90]
I'm using 3rd party input method called "Openvanilla"
Word selection box display on edge instead of typing area as shown.
The selection box display perfect in all other circumstances (e.g. Note as shown)

This problem wasn't appear in older version of Aegisub r8942
Sadly r8942 crash on Mac Sonoma
So I must solve this problem or forever stuck with Mac Monterey 

Any idea?

Issue
<img width="1034" alt="Screenshot 2023-09-28 at 10 11 15 am" src="https://github.com/arch1t3cht/Aegisub/assets/134396014/fc5a390f-e316-4ad8-9bd5-675ca30d98c6">
Correct 
<img width="400" alt="Screenshot 2023-09-28 at 10 11 34 am" src="https://github.com/arch1t3cht/Aegisub/assets/134396014/b6c5bf74-cae1-431b-918f-d08f0f7dc065">

**Comment by arch1t3cht** [comment]
See https://github.com/arch1t3cht/Aegisub/issues/91#issuecomment-1783044832
