### ISSUE TITLE
Crash after opening a video file

### ISSUE THREAD

**Issue by HxxThSwggr** [arch1t3cht/Aegisub#93]
Whenever I try to open any video (have not tested many formats) Aegisub crashes after a bit of indexing.
EDIT: Dummy video crashes as well!

If run in a terminal, reports this error:
`Gdk-Message: 12:37:59.922: Error 71 (Protocol error) dispatching to Wayland display.`

Audio can be opened without problems.

**OS:**  Arch Linux (zen)
**Wayland**
**Aegisub:** Installed from [AUR](https://aur.archlinux.org/packages/aegisub-arch1t3cht-git)
**Video provider:** FFmpegSource

**Comment by seproDev** [comment]
This is a wxWidgets bug https://github.com/wxWidgets/wxWidgets/issues/23961

**Comment by HxxThSwggr** [comment]
Ah, I see that they are already working on it. I'll wait for it to update then. Thanks.
