### ISSUE TITLE
Array concatenation error on LuaJIT meson script

### ISSUE THREAD

**Issue by jgmdev** [arch1t3cht/Aegisub#98]
Hi, I was using your meson build scripts for [pragtical editor](https://github.com/pragtical/pragtical) for which I created a PR https://github.com/pragtical/pragtical/pull/43 and when building on the github CI got the error:

> ERROR: Could not get define '1'

I thought it was a meson error and even opened some issue on meson repo :facepalm: https://github.com/mesonbuild/meson/issues/12512 but in reality it is just an array concatenation mistake which the following patch fixes.

[subprojects/packagefiles/luajit/src/host/meson.build](https://github.com/pragtical/pragtical/pull/43/commits/a21ba4b0944969b6bada893d30773c3df8d0ba48)
```diff
 if host_machine.cpu_family() == 'x86'
-    checkdefs += ['__SSE2__', '1', ['-D', 'SSE']]
+    checkdefs += [
+        ['__SSE2__', '1', ['-D', 'SSE']]
+    ]
 endif
 
 foreach def: checkdefs
```
Thanks for your contributions!

**Comment by arch1t3cht** [comment]
Hi - GitHub decided to not send me a notification for this, so I missed this until now. I also have no idea how this didn't error on this repo's CI before, but oh well. Thanks for pointing this out, I fixed it now.

**Comment by arch1t3cht** [comment]
...oh
https://github.com/arch1t3cht/Aegisub/blob/6a60f9a02ef8e75db9c11eed84c7c346f2544fb8/subprojects/packagefiles/luajit/src/host/meson.build#L28

**Comment by arch1t3cht** [comment]
Looking into it more, I'm not sure where this check and define even comes from. Maybe this was in the Makefile back when myaa initially wrote this wrap (though I couldn't even find it anywhere in the luajit history), but it's certainly not in there now. So I'll just remove the whole if block.

**Comment by jgmdev** [comment]
> but it's certainly not in there now. So I'll just remove the whole if block.

Thanks for the heads up!
