### ISSUE TITLE
'Toolbar Icon Size' broken?

### ISSUE THREAD

**Issue by McBaws** [arch1t3cht/Aegisub#99]
Feature release 10 and 11 have different behaviour when it comes to this option. 

I am using a 3072x1920 display at 175% scaling on Windows. Haven't tested this on any other machines.

Feature release 10:
![Size 23](https://github.com/arch1t3cht/Aegisub/assets/32965045/1e396ba3-92ba-4d73-b196-4c55246e2846)
![Size 24](https://github.com/arch1t3cht/Aegisub/assets/32965045/63faa1ec-4f49-49e3-a59a-cc153bdd2a0c)
![Size 32](https://github.com/arch1t3cht/Aegisub/assets/32965045/a328b4da-d596-4837-94cb-eeae7905e0d9)

Feature release 11:
![Size 23](https://github.com/arch1t3cht/Aegisub/assets/32965045/2b9e344e-0b4a-4428-8e63-34038ef6f790)
![Size 24](https://github.com/arch1t3cht/Aegisub/assets/32965045/56f4a0ef-48dd-485f-9ca1-33716d0e0ed9)
![Size 32](https://github.com/arch1t3cht/Aegisub/assets/32965045/593b4005-4247-4f2c-8e47-6ace7d02a0fe)

As you can see, in release 11 the icons start off with a larger size, and the icons are weirdly pixelated. Could this be linked to the scaling factor?

It seems like the icons have the same pixellation at different sizes on both releases, but the icons are just bigger in 11, making them look weird.

**Comment by arch1t3cht** [comment]
I verified now that this was due to bumping wxWidgets from 3.1.4 to 3.1.7. Nothing regarding icon scaling changed in Aegisub's code since feature_10 either.
I'll look into this more when I have time, but if all else fails I'll just see if I can revert the bump for now.
